title: Core Triggers
icon: IconStreamerbot
aside.level: 3
category.title: Core Triggers
category.icon: IconStreamerbot
navigation.title: Core
navigation.description: Triggers for core Streamer.bot features