title: C# Methods
description: Reference of all C# methods available in Streamer.bot
icon: mdi:code-braces-box
navigation:
  title: C# Methods
  icon: mdi:code-braces-box
ogImage:
  headline: C# Methods