title: YouTube Triggers
icon: mdi:youtube
aside.level: 3
category.title: YouTube Triggers
category.icon: mdi:youtube
navigation.title: YouTube
navigation.description: React to YouTube events with Streamer.bot