title: Meld Studio Triggers
icon: IconMeldStudio
category.title: Meld Studio Triggers
category.icon: IconMeldStudio
navigation.title: Meld Studio
navigation.description: React to Meld Studio events with Streamer.bot