title: PolyPop Sub-Actions
icon: IconPolyPop
aside.level: 3
category.title: PolyPop Sub-Actions
category.icon: IconPolyPop
navigation.title: PolyPop
navigation.description: Trigger alerts in PolyPop Live