title: Meld Studio Sub-Actions
icon: IconMeldStudio
navigation.title: Meld Studio
navigation.description: Control Meld Studio with Streamer.bot
category.title: Meld Studio
category.icon: IconMeldStudio