title: mtion Sub-Actions
icon: IconMtionStudio
aside.level: 4
category.title: mtion Sub-Actions
category.icon: IconMtionStudio
navigation.title: mtion
navigation.description: Control mtion Studio with Streamer.bot