title: C# Classes
description: Reference of all C# classes available in Streamer.bot
icon: mdi:code-braces-box
navigation:
  title: C# Classes
  icon: mdi:code-braces-box
ogImage:
  headline: C# Classes