title: Streamlabs Desktop Sub-Actions
icon: IconStreamlabsDesktop
aside.level: 3
category.title: Streamlabs Desktop Sub-Actions
category.icon: IconStreamlabsDesktop
navigation.title: Streamlabs Desktop
navigation.description: Control your Streamlabs Desktop broadcast